### ISSUE TITLE
Error when skip_stride is None

### ISSUE THREAD

**Issue by tyumru** [NVlabs/conv-tt-lstm#1]
`skip_stride` in the following lines should be changed to `self.skip_stride`

https://github.com/NVlabs/conv-tt-lstm/blob/e31c4f74b3e8e7101de1c999c0000ed47ea90feb/code/convlstmnet.py#L113-L114

**Comment by alexshaodong** [comment]
> `skip_stride` in the following lines should be changed to `self.skip_stride`
> 
> https://github.com/NVlabs/conv-tt-lstm/blob/e31c4f74b3e8e7101de1c999c0000ed47ea90feb/code/convlstmnet.py#L113-L114

Hello, I had an error loading the data：
(base) root@ubuntu:~/sdw/conv-tt-lstm/code# python3 model_train.py --dataset MNIST --batch-size 8 --use-sigmoid --img-height 64 --img-width 64 --kernel-size 5 --model convttlstm --model-order 3 --model-steps 3 --model-rank 8 --learning-rate 1e-4 --gradient-clipping --clipping-threshold 3
Traceback (most recent call last):
  File "model_train.py", line 295, in <module>
    main(parser.parse_args())
  File "model_train.py", line 64, in main
    "height": args.img_height, "width": args.img_width, "channels": args.img_channels})
  File "/root/sdw/conv-tt-lstm/code/dataloader.py", line 29, in __init__
    self.data = np.float32(np.load(path)["data"] / 255.0)
  File "/root/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'data is not a file in the archive'
Can you give me some help, please? Thank you！

**Comment by Leesoon1984** [comment]
Can you provide a link to load the moving minist2 dataset?

**Comment by wonmin-byeon** [comment]
> `skip_stride` in the following lines should be changed to `self.skip_stride`
> 
> https://github.com/NVlabs/conv-tt-lstm/blob/e31c4f74b3e8e7101de1c999c0000ed47ea90feb/code/convlstmnet.py#L113-L114

@tyumru Sorry for the late reply. It was a bug. We updated the code now.
