### ISSUE TITLE
Possbile error in convlstmcell.py

### ISSUE THREAD

**Issue by asfjac** [NVlabs/conv-tt-lstm#2]
Guess the last line in convlstmcell.py should be 

self.hidden_pointer = (self.hidden_pointer + 1) % self.steps

instead of 

self.hidden_pointer = (self.hidden_pointer + 1) % self.order

Cuz otherwise only self.order hidden states would be updated instead of self.steps

**Comment by alexshaodong** [comment]
> Guess the last line in convlstmcell.py should be
> 
> self.hidden_pointer = (self.hidden_pointer + 1) % self.steps
> 
> instead of
> 
> self.hidden_pointer = (self.hidden_pointer + 1) % self.order
> 
> Cuz otherwise only self.order hidden states would be updated instead of self.steps

Hello, I had an error loading the data：
(base) root@ubuntu:~/sdw/conv-tt-lstm/code# python3 model_train.py --dataset MNIST --batch-size 8 --use-sigmoid --img-height 64 --img-width 64 --kernel-size 5 --model convttlstm --model-order 3 --model-steps 3 --model-rank 8 --learning-rate 1e-4 --gradient-clipping --clipping-threshold 3
Traceback (most recent call last):
File "model_train.py", line 295, in
main(parser.parse_args())
File "model_train.py", line 64, in main
"height": args.img_height, "width": args.img_width, "channels": args.img_channels})
File "/root/sdw/conv-tt-lstm/code/dataloader.py", line 29, in init
self.data = np.float32(np.load(path)["data"] / 255.0)
File "/root/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 262, in getitem
raise KeyError("%s is not a file in the archive" % key)
KeyError: 'data is not a file in the archive'
Can you give me some help, please? Thank you！

**Comment by wonmin-byeon** [comment]
> Guess the last line in convlstmcell.py should be
> 
> self.hidden_pointer = (self.hidden_pointer + 1) % self.steps
> 
> instead of
> 
> self.hidden_pointer = (self.hidden_pointer + 1) % self.order
> 
> Cuz otherwise only self.order hidden states would be updated instead of self.steps

@asfjac Sorry for the late reply. It was a bug. Thanks for pointing it out.
